# -*- coding: utf-8 -*-
"""Practice Codes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OquDbOmDu8DG33HyRVQY87AtTMC-GJBx
"""

# write a program to read employee data from the keyword and print that data?

emp_no = int(input("Employee's No.? "))
emp_name = input("Employee's name? ")
emp_salary = int(input("Employee's salary? "))
emp_add = input("Employee's address? ")
emp_relation = bool(input("Is married? "))

print("Employee's No. is: ", emp_no)
print("Employee's name is: ", emp_name)
print(f"Employee's salary: {emp_salary}")
print("Employee's address: ", emp_add)
print("Employee's salary: ", emp_relation)

# 2. Write a program to read 3 float numbers from the keyboard with, seperator and print their sum?

# Input numbers as a single string
numbers = input("Enter three float numbers separated by commas: ")

# Split the input string into a list
number_strings = numbers.split(',')

# Convert each string to a float
num1 = float(number_strings[0])
num2 = float(number_strings[1])
num3 = float(number_strings[2])

# Display the result
print(f"The sum of the numbers is: {num1 + num2 + num3}")

def convert_to_fahrenheit(celsius):
    fahrenheit = celsius * 9 / 5 + 32  # Correct the spelling and calculation
    return fahrenheit  # Correct return variable name

# Test the function with a known value
print("The temperature in Fahrenheit:", convert_to_fahrenheit(0))

for x in range(10, 0, -1):
   print(x, end = ' ')

n = int(input("Enter the number of rows: "))

for i in range(1, n + 1):
    print('* ' * i)

n = int(input("Enter the number of rows: "))

for i in range(n, 0, -1):
    print('* ' * i)

n = int(input("Enter the number of rows: "))

for i in range(1, n + 1):
    print(" " * (n - i), end="")

    print("*" * (2 * i - 1))

n = int(input("Enter the number of rows: "))

for i in range(n, 0, -1):
    print(" " * (n - i), end="")

    print("*" * (2 * i - 1))

n = int(input("Enter the number of rows: "))

def pyramid():
    for i in range(1, n + 1):
        print(" " * (n - i), end="")
        print("*" * (2 * i - 1))

def inv_pyramid():
  for i in range(n-1, 0, -1):
    print(" " * (n - i), end="")
    print("*" * (2 * i - 1))

pyramid()
inv_pyramid()

main_string = input("Enter the main string: ")
substring = input("Enter the substring to search for: ")

start = 0

while True:
    position = main_string.find(substring, start)

    if position == -1:
        break

    print(f"Substring found at position: {position}")

    start = position + 1

def reverse_words(sentence):

    words = sentence.split()
    reversed_words = words[::-1]

    reversed_sentence = " ".join(reversed_words)
    return reversed_sentence

sentence = input("Enter a sentence: ")

reversed_sentence = reverse_words(sentence)
print(f"Reversed sentence: {reversed_sentence}")